import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pizza Special Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpeg',
    tags: ['FastFood', 'Pizza Special', 'Lunch Special'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpeg',
    tags: ['Slow-Food', 'Lunch Special'],
  },
  {
    id:'3',
    name: 'Burger ',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpeg',
    tags: ['FastFood', 'Burger '],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fried-Foods'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['Slow-Food', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza Special',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza Special', 'Lunch Special'],
  },
  {
    id:'7',
    name: 'Spicy Cheese Burger',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Indian'],
    stars: 4.0,
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Burger', 'Lunch Special'],
  },
  {
    id:'8',
    name: 'Vegetables Magento Pizza Special',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Pizza Special', 'Lunch Special'],
  },
  {
    id:'9',
    name: 'Special Burger',
    cookTime: '10-30',
    price: 50,
    favorite: false,
    origins: ['italy'],
    stars: 4.8,
    imageUrl: 'assets/food-9.jpeg',
    tags: ['FastFood', 'Burger', 'Lunch Special'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 9 },
  { name: 'FastFood', count: 7 },
  { name: 'Pizza Special', count: 3 },
  { name: 'Lunch Special', count: 6 },
  { name: 'Slow-Food', count: 2 },
  { name: 'Burger', count: 2 },
  { name: 'Fried-Foods', count: 1 },
  { name: 'Soup', count: 1 },
]
